name: Sprint boot CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
   checkout:
    runs-on: ubuntu-latest
    # runs-on: self-hosted  # Uncomment if using a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
   build:
    runs-on: ubuntu-latest
    needs: checkout
    # runs-on: self-hosted  # Uncomment if using a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Setup java
        uses: actions/setup-java@v4
        with:
         distribution: 'temurin'
         java-version: '21'
         check-latest: true
      
      - name: unit test
        run: |
            mvn test
            mvn compile
      
   trivyscan:
     runs-on: ubuntu-latest
     needs: build
     # runs-on: self-hosted  # Uncomment if using a self-hosted runner

     steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Run Trivy scan on Maven project
        uses: aquasecurity/trivy-action@0.14.0  # Use a stable release tag
        with:
          scan-type: fs
          scan-ref: .
          format: table
          ignore-unfixed: true
          severity: CRITICAL,HIGH,MEDIUM
          output: report.trivy-html
          
      - name: Upload Trivy HTML report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-html-report
          path: report.trivy-html

 

 
      
      
      
      
     
