name: Sprint boot CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
   checkout:
    runs-on: ubuntu-latest
    # runs-on: self-hosted  # Uncomment if using a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
   build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted  # Uncomment if using a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - uses: actions/setup-java@v4
        with:
         distribution: 'temurin'
         java-version: '21'
         check-latest: true
      

 
      
      
      
      
     
